
services:
  phpfpm:
    image: nginx:latest
    volumes:
      - codebase:/var/www/html
    working_dir: /var/www/html
    #environment:
      # Additional environment variables if needed
    networks:
      - maho_network

  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - codebase:/var/www/html:ro   # Mount maho codebase as read-only
      - sslcerts:/etc/nginx/ssl:ro  # Mount SSL volume as read-only
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - phpfpm
    networks:
      - maho_network

  mkcert:
    image: mkcert-maho
    volumes:
      - sslcerts:/certs  # Use SSL volume for storing certificates
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - maho_network

volumes:
  codebase:
    driver: local  # MaHo codebase
  sslcerts:
    driver: local  # Define a volume for SSL certificates

networks:
  maho_network:
    driver: bridge
