name: Build and Push Docker Images

on:
  push:
    paths:
      - 'docker-images/**'  # Trigger only when there are changes in this folder

jobs:

  build-php:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-php
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker-images/php82
          push: true
          tags: ghcr.io/${{ github.repository }}/php82:latest
          cache-from: type=local,src=/tmp/.buildx-cache-php
          cache-to: type=local,dest=/tmp/.buildx-cache-php